### ISSUE TITLE
游客

### ISSUE THREAD

**Issue by muchen149** [zhouzishu/GitHubLogin#1]
你好 我测试倒是登录成功了  不过有几个问题咨询一下   两种     1。后台设定的自动注册评论者  2.超级管理员   自动登陆时是怎么识别自动登录超级管理员的  是根据当时登录操作的账号进行了记录还是根据最高层级ID判断的      现在测试多了一直404 binding.php页面

**Comment by muchen149** [comment]
比如说我登陆朋友的账户之后  但我想注销掉通过github第三方登录登陆自己的账户  这时候会不会把我的github绑定到我朋友的账户记录一起去了

**Comment by zhouzishu** [comment]
不会，一个git账号只绑定一个账户
